build: update GitHub Actions workflow to trigger on opened pull requests and check for 'ready-to-deploy' label

diff --git a/.github/workflows/03-release.yml b/.github/workflows/03-release.yml
--- a/.github/workflows/03-release.yml
+++ b/.github/workflows/03-release.yml
@@ -2,16 +2,20 @@ name: Deploy to Production
 
 on:
   pull_request:
-    types: [labeled, unlabeled]
+    types: [labeled, unlabeled, opened]
+    branches:
+      - 'release/**'    
     
 
 jobs:
   deploy:
-    if: contains(github.event.pull_request.labels.*.name, 'deploy-to-production')
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+      - name: Check for 'ready-to-deploy' label
+        if: ${{ !contains(github.event.pull_request.labels.*.name, 'ready-to-deploy') }}
+        run: |
+          echo "Error: The pull request does not have the 'ready-to-deploy' label."
+          exit 1
 
       - name: Deploy to Production
         run: |
